# Generated by Django 6.0.2 on 2026-02-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carusel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carusel/'),
        ),
    ]
